name: Molecule Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  molecule:
    name: Run Tests
    strategy:
      matrix:
        os:
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
        env:
          ANSIBLE_FORCE_COLOR: "1"
